name: Get Citation Data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install requirements
        run: |
          pip3 install -r google_scholar_crawler/requirements.txt
      - name: Fetch Google Scholar citation data
        run: |
          cd google_scholar_crawler
          python3 main.py
          cd results
          git init
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add *.json
          git commit -m "Updated Citation Data"
          git push "${remote_repo}" HEAD:google-scholar-stats --force
        env:
          GOOGLE_SCHOLAR_ID: ikFB2JcAAAAJ
